#include "global.h"
#include "battle.h"
#include "battle_util.h"
#include "sprite.h"
#include "constants/species.h"
#include "pmd_gba_runtime.h"
#include "pmd_soulgold_adapter.h"
#include "pmd_soulgold_prototype.h"

// Generated by tools/pmd_gba_emit_c.py after player/opponent conversion.
extern const struct PmdGbaAction gPmdCyndaquilPlayerWalkAction;
extern const struct PmdGbaAction gPmdCyndaquilOpponentWalkAction;

static bool8 sBound[PMD_GBA_MAX_BATTLERS];
static u8 sBoundSpriteId[PMD_GBA_MAX_BATTLERS];

static void ClearBinding(u8 battler)
{
    if (battler >= PMD_GBA_MAX_BATTLERS)
        return;
    if (sBound[battler])
        PmdGbaRuntime_Unbind(battler);
    sBound[battler] = FALSE;
    sBoundSpriteId[battler] = SPRITE_NONE;
}

void PmdSoulGoldPrototype_Init(void)
{
    u8 battler;

    PmdSoulGold_Init();
    for (battler = 0; battler < PMD_GBA_MAX_BATTLERS; battler++)
    {
        sBound[battler] = FALSE;
        sBoundSpriteId[battler] = SPRITE_NONE;
    }
}

void PmdSoulGoldPrototype_OnBattlerSpriteReady(u8 battler)
{
    // A battler slot may reuse the exact same Sprite ID after switch/reshow.
    // Treat sprite creation as an explicit generation boundary instead of
    // trying to infer replacement from IDs or pointer values.
    ClearBinding(battler);
}

void PmdSoulGoldPrototype_Tick(void)
{
    u8 battler;

    for (battler = 0; battler < PMD_GBA_MAX_BATTLERS; battler++)
    {
        const struct PmdGbaAction *action;
        u16 species;
        u8 spriteId;

        if (battler >= gBattlersCount)
        {
            ClearBinding(battler);
            continue;
        }

        species = GetBattlerVisualSpecies(battler);
        spriteId = gBattlerSpriteIds[battler];

        if (species != SPECIES_CYNDAQUIL)
        {
            ClearBinding(battler);
            continue;
        }

        // Keep a secondary polling guard in addition to the explicit
        // OnBattlerSpriteReady hook. This catches any host path we have not yet
        // instrumented without making Sprite ID equality the primary authority.
        if (sBound[battler] && sBoundSpriteId[battler] != spriteId)
            ClearBinding(battler);

        if (!sBound[battler])
        {
            action = GetBattlerSide(battler) == B_SIDE_PLAYER
                ? &gPmdCyndaquilPlayerWalkAction
                : &gPmdCyndaquilOpponentWalkAction;

            if (PmdGbaRuntime_Bind(battler, action))
            {
                sBound[battler] = TRUE;
                sBoundSpriteId[battler] = spriteId;
            }
        }
    }

    PmdGbaRuntime_Tick();
}

void PmdSoulGoldPrototype_Reset(void)
{
    u8 battler;

    for (battler = 0; battler < PMD_GBA_MAX_BATTLERS; battler++)
        ClearBinding(battler);
    PmdSoulGold_Reset();
}
