#!/usr/bin/env python3
"""Generate the minimal GBARecomp base config for a source-built SoulGold ROM.

The ROM, ELF and MAP are expected to come from the same pinned SoulGold build.
This script deliberately computes identity from the actual ROM produced by CI
instead of carrying a hand-copied hash.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

EXPECTED_SIZE = 32 * 1024 * 1024


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--rom", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--symbols", default="symbols/imported_symbols.tsv")
    ap.add_argument("--boundaries", default="symbols/function_boundaries.tsv")
    ap.add_argument("--generated", default="generated")
    args = ap.parse_args()

    blob = args.rom.read_bytes()
    if len(blob) != EXPECTED_SIZE:
        raise SystemExit(
            f"SoulGoldRecomp R0 expects a 32 MiB source-built ROM; got {len(blob)} bytes"
        )

    sha1 = hashlib.sha1(blob).hexdigest()
    sha256 = hashlib.sha256(blob).hexdigest()

    text = f'''# Auto-generated by tools/make_soulgold_recomp_config.py.
# Identity is tied to the exact source-built ROM used for ELF/MAP symbol import.

[program]
name = "Pokemon SoulGold v1.0.5 source-build"
id = "soulgold_v105"
load_address = 0x08000000
size = 0x02000000
entry_pc = 0x08000000
codegen_shards = 64
static_resume_all = true

[identity]
sha1 = "{sha1}"

[recompiler]
entry_point = "0x08000000"
seeds = "{args.symbols}"
boundaries = "{args.boundaries}"
out_dir = "{args.generated}"
strict = false

[save]
type = "flash1m"

[runtime]
debug_port = 19905
window_title = "SoulGoldRecomp"

[functions]
arm = []
thumb = []
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8", newline="\n")
    print(f"rom_sha1={sha1}")
    print(f"rom_sha256={sha256}")
    print(f"rom_bytes={len(blob)}")
    print(f"config={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
